const imgStyle = "w-[250px]";

export const loadingRandomImgArray = [
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-132.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2024/01/out-transparent-1.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/04/out-transparent-2.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2022/10/out-transparent-1.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/01/out-transparent-2.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/01/out-transparent-6.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-135.gif?resize=840%2C1008&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-128.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-131.gif?resize=560%2C653&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-132.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-116.gif?resize=560%2C753&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-103.gif?resize=840%2C840&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-99.gif?resize=840%2C897&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-73.gif?resize=560%2C526&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-54.gif?resize=560%2C542&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-20.gif?resize=840%2C610&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-12.gif?resize=560%2C560&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-15.gif?resize=840%2C822&ssl=1"
    alt=""
  />,
  <img
    className={imgStyle}
    src="https://i0.wp.com/walfiegif.wordpress.com/wp-content/uploads/2023/07/out-transparent-61.gif?resize=560%2C650&ssl=1"
    alt=""
  />,
];
