import type { Metadata } from "next";
import "./globals.css";
// pages/_app.js 또는 _app.tsx
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Font Awesome 스타일을 가져옵니다.
config.autoAddCss = false; // 기본적으로 스타일을 자동으로 추가하지 않도록 설정

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head></head>
      <body className={"antialiased bg-black"}>
        {children}
        <div id="global-modal"></div>
      </body>
    </html>
  );
}
